.PHONY: clean All

All:
	@echo "----------Building project:[ pp10a - Debug ]----------"
	@cd "pp10a" && "$(MAKE)" -f  "pp10a.mk"
clean:
	@echo "----------Cleaning project:[ pp10a - Debug ]----------"
	@cd "pp10a" && "$(MAKE)" -f  "pp10a.mk" clean
